name: Scheduled Events

on:
  schedule:
  - cron: '0 */1 * * *' #runs every 1 hour

jobs:
  show-info:
    runs-on: ubuntu-latest
    steps: 
    - name: info
      run: |
        echo "This is a scheduled tasks running at every 5 minutes"
      
  
  
